import { TechSchemaType } from "ti4-ttpg-ts";

export const SOURCE_TO_TECH_DATA: Record<string, Array<TechSchemaType>> = {
    "discordant-stars": [
    {
        name: "Aegis II",
        nsidName: "aegis-2",
        color: "unit-upgrade",
        prerequisites: { blue: 2, yellow: 1 },
        isFactionTech: true,
        replacesNsidName: "dreadnought-2",
    },
    {
        name: "Blockade Runner II",
        nsidName: "bloackade-runner-2",
        color: "unit-upgrade",
        prerequisites: { red: 2 },
        isFactionTech: true,
        replacesNsidName: "destroyer-2",
    },
    {
        name: "Chitin Hulk II",
        nsidName: "chitin-hulk-2",
        color: "unit-upgrade",
        prerequisites: { blue: 2, yellow: 1 },
        isFactionTech: true,
        replacesNsidName: "dreadnought-2",
        
    },
    {
        name: "Combat Transport II",
        nsidName: "combat-transport-2",
        color: "unit-upgrade",
        prerequisites: { blue: 2 },
        isFactionTech: true,
        replacesNsidName: "carrier-2",
    },
    {
        name: "Corsair II",
        nsidName: "corsair-2",
        color: "unit-upgrade",
        prerequisites: { blue: 1, green: 1 },
        isFactionTech: true,
        replacesNsidName: "fighter-2",
    },
    {
        name: "Gauss Cannon II",
        nsidName: "gauss-cannon-2",
        color: "unit-upgrade",
        prerequisites: { yellow: 1, red: 1 },
        isFactionTech: true,
        replacesNsidName: "pds-2",
    },
    {
        name: "Heavy Bomber II",
        nsidName: "heavy-bomber-2",
        color: "unit-upgrade",
        prerequisites: { blue: 1, green: 1 },
        isFactionTech: true,
        replacesNsidName: "fighter-2",
    },
    {
        name: "Impactor II",
        nsidName: "impactor-2",
        color: "unit-upgrade",
        prerequisites: { green: 2 },
        isFactionTech: true,
        replacesNsidName: "infantry-2",
    },
    {
        name: "Lancer Dreadnought II",
        nsidName: "lancer-dreadnought-2",
        color: "unit-upgrade",
        prerequisites: { blue: 2, yellow: 1 },
        isFactionTech: true,
        replacesNsidName: "dreadnought-2",
    },
    {
        name: "Mycelium Ring II",
        nsidName: "mycelium-ring-2",
        color: "unit-upgrade",
        prerequisites: { yellow: 2 },
        isFactionTech: true,
        replacesNsidName: "space-dock-2",
    },
    {
        name: "Orion Platform II",
        nsidName: "orion-platform-2",
        color: "unit-upgrade",
        prerequisites: { yellow: 1, red: 1 },
        isFactionTech: true,
        replacesNsidName: "pds-2",
    },
    {
        name: "Raider II",
        nsidName: "raider-2",
        color: "unit-upgrade",
        prerequisites: { green: 1, yellow: 1, red: 1 },
        isFactionTech: true,
        replacesNsidName: "cruiser-2",
    },
    {
        name: "Sabre II",
        nsidName: "sabre-2",
        color: "unit-upgrade",
        prerequisites: { red: 2 },
        isFactionTech: true,
        replacesNsidName: "destroyer-2",
    },
    {
        name: "Shattered Sky II",
        nsidName: "shattered-sky-2",
        color: "unit-upgrade",
        prerequisites: { green: 1, yellow: 1, red: 1 },
        isFactionTech: true,
        replacesNsidName: "cruiser-2",
    },
    {
        name: "Star Dragon II",
        nsidName: "star-dragon-2",
        color: "unit-upgrade",
        prerequisites: { blue: 2 },
        isFactionTech: true,
        replacesNsidName: "carrier-2",
    },
    {
      nsidName: "terrafactory-2",
      name: "Terrafactory II",
      color: "unit-upgrade",
      prerequisites: { red: 3, yellow: 1 },
      isFactionTech: true,
      replacesNsidName: "war-sun-2",
    },
    {
        name: "Trade Port II",
        nsidName: "trade-port-2",
        color: "unit-upgrade",
        prerequisites: { yellow: 2 },
        isFactionTech: true,
        replacesNsidName: "space-dock-2",
    },
    {
        name: "Unholy Abomination II",
        nsidName: "unholy-abomination-2",
        color: "unit-upgrade",
        prerequisites: { green: 2 },
        isFactionTech: true,
        replacesNsidName: "infantry-2",
    },
    {
        name: "Voidflare Warden II",
        nsidName: "void-flare-warden-2",
        color: "unit-upgrade",
        prerequisites: { green: 1, yellow: 1, red: 1 },
        isFactionTech: true,
    },
    {
      nsidName: "geosympathic-impeller",
      name: "Geosympathic Impeller",
      color: "blue",
      prerequisites: { blue: 1 },
      abbr: "Geo Imp",
      isFactionTech: true,
    },
    {
      nsidName: "lightning-drives",
      name: "Lightning Drives",
      color: "blue",
      prerequisites: { blue: 3 },
      abbr: "Light Drive",
      isFactionTech: true,
    },
    {
      nsidName: "midas-turbine",
      name: "Midas Turbine",
      color: "blue",
      prerequisites: { blue: 1 },
      abbr: "Midas",
      isFactionTech: true,
    },
    {
      nsidName: "pilgrimage-beacons",
      name: "Pilgrimage",
      color: "blue",
      prerequisites: { blue: 2 },
      abbr: "Pil Beacons",
      isFactionTech: true,
    },
    {
      nsidName: "rift-engines",
      name: "Rift Engines",
      color: "blue",
      prerequisites: { blue: 1 },
      abbr: "Rift Eng",
      isFactionTech: true,
    },
    {
      nsidName: "shrouded-skirmishers",
      name: "Shrouded Skirmisher",
      color: "blue",
      prerequisites: { blue: 1 },
      abbr: "Shroud",
      isFactionTech: true,
    },
    {
      nsidName: "spark-thrusters",
      name: "Spark Thrusters",
      color: "blue",
      prerequisites: { blue: 2 },
      abbr: "Spark",
      isFactionTech: true,
    },
    {
      nsidName: "wraith-engine",
      name: "Wraith Engine",
      color: "blue",
      prerequisites: { blue: 2 },
      abbr: "Wraith Eng",
      isFactionTech: true,
    },
    {
      nsidName: "applied-biothermics",
      name: "Applied Biothermics",
      color: "green",
      prerequisites: { green: 2 },
      abbr: "App Bio",
      isFactionTech: true,
    },
    {
      nsidName: "blackmail-programs",
      name: "Blackmail Programs",
      color: "green",
      prerequisites: { green: 2 },
      abbr: "Blackmail",
      isFactionTech: true,
    },
    {
      nsidName: "broker-network",
      name: "Broker Network",
      color: "green",
      prerequisites: { green: 1 },
      abbr: "Broker",
      isFactionTech: true,
    },
    {
      nsidName: "envoy-network",
      name: "Envoy Network",
      color: "green",
      prerequisites: { green: 1 },
      abbr: "Envoy",
      isFactionTech: true,
    },
    {
      nsidName: "indoctrination-teams",
      name: "Indoctrination Teams",
      color: "green",
      prerequisites: { green: 2 },
      abbr: "Indoc",
      isFactionTech: true,
    },
    {
      nsidName: "networked-command",
      name: "Networked Command",
      color: "green",
      prerequisites: { green: 1 },
      abbr: "Net Comm",
      isFactionTech: true,
    },
    {
      nsidName: "psychoactive-armaments",
      name: "Psychoactive Armaments",
      color: "green",
      prerequisites: { green: 2 },
      abbr: "Psy Arm",
      isFactionTech: true,
    },
    {
      nsidName: "psychographics",
      name: "Psychographics",
      color: "green",
      prerequisites: { green: 3 },
      abbr: "Psy Graph",
      isFactionTech: true,
    },
    {
      nsidName: "stones-embrace",
      name: "Stones Embrace",
      color: "green",
      prerequisites: { green: 2 },
      abbr: "Stone",
      isFactionTech: true,
    },
    {
      nsidName: "tempest-drive",
      name: "Tempest Drive",
      color: "green",
      prerequisites: { green: 2 },
      abbr: "Tempest",
      isFactionTech: true,
    },
    {
      nsidName: "unity-algorithm",
      name: "Unity Algorithm",
      color: "green",
      prerequisites: { green: 3 },
      abbr: "Unity",
      isFactionTech: true,
    },
    {
      nsidName: "war-song-implants",
      name: "War Song Implants",
      color: "green",
      prerequisites: { green: 3 },
      abbr: "WSI",
      isFactionTech: true,
    },
    {
      nsidName: "zhrgar-stimulants",
      name: "Zhrgar Simulants",
      color: "green",
      prerequisites: { green: 1 },
      abbr: "Zhrgar",
      isFactionTech: true,
    },
    {
      nsidName: "ats-armaments",
      name: "ATS Armaments",
      color: "red",
      prerequisites: { red: 2 },
      abbr: "ATS",
      isFactionTech: true,
    },
    {
      nsidName: "brood-pod",
      name: "Brood Pod",
      color: "red",
      prerequisites: { red: 2 },
      abbr: "Brood",
      isFactionTech: true,
    },
    {
      nsidName: "deliverance-engine",
      name: "Deliverance Engine",
      color: "red",
      prerequisites: { red: 2 },
      abbr: "D Engine",
      isFactionTech: true,
    },
    {
      nsidName: "emergency-mobilization",
      name: "Emergency Mobilization",
      color: "red",
      prerequisites: { red: 2 },
      abbr: "E Mobile",
      isFactionTech: true,
    },
    {
      nsidName: "false-flag-operation",
      name: "False Flag Operation",
      color: "red",
      prerequisites: { red: 1 },
      abbr: "FFO",
      isFactionTech: true,
    },
    {
      nsidName: "fractal-plating",
      name: "Fractal Plating",
      color: "red",
      prerequisites: { red: 2 },
      abbr: "Fractal",
      isFactionTech: true,
    },
    {
      nsidName: "omniscience-field",
      name: "Omniscience Field",
      color: "red",
      prerequisites: { red: 3 },
      abbr: "Omni",
      isFactionTech: true,
    },
    {
      nsidName: "orbital-defense-grid",
      name: "Orbital Defense Grid",
      color: "red",
      prerequisites: { red: 2 },
      abbr: "ODG",
      isFactionTech: true,
    },
    {
      nsidName: "scavenger-exos",
      name: "Scavenger Exos",
      color: "red",
      prerequisites: { red: 1 },
      abbr: "Exos",
      isFactionTech: true,
    },
    {
      nsidName: "seidr-project",
      name: "Seidr Project",
      color: "red",
      prerequisites: { red: 2 },
      abbr: "Seidr",
      isFactionTech: true,
    },
    {
      nsidName: "shard-volley",
      name: "Seidr Project",
      color: "red",
      prerequisites: { red: 1 },
      abbr: "Shard",
      isFactionTech: true,
    },
    {
      nsidName: "contractual-obligations",
      name: "Contractual Obligations",
      color: "yellow",
      prerequisites: { yellow: 2 },
      abbr: "Contract",
      isFactionTech: true,
    },
    {
      nsidName: "covert-strike-teams",
      name: "Covert Strike Teams",
      color: "yellow",
      prerequisites: { yellow: 2 },
      abbr: "Covert",
      isFactionTech: true,
    },
    {
      nsidName: "daedalon-flight-system",
      name: "Daedalon Flight System",
      color: "yellow",
      prerequisites: { yellow: 1 },
      abbr: "DFS",
      isFactionTech: true,
    },
    {
      nsidName: "emergency-deployment",
      name: "Emergency Deployment",
      color: "yellow",
      prerequisites: { yellow: 2 },
      abbr: "eDeploy",
      isFactionTech: true,
    },
    {
      nsidName: "encrypted-trade-hub",
      name: "Encrypted Trade Hub",
      color: "yellow",
      prerequisites: { yellow: 2 },
      abbr: "ETH",
      isFactionTech: true,
    },
    {
      nsidName: "fabrication-grid",
      name: "Fabrication Grid",
      color: "yellow",
      prerequisites: { yellow: 2 },
      abbr: "Fab",
      isFactionTech: true,
    },
    {
      nsidName: "impressment-programs",
      name: "Impressment Programs",
      color: "yellow",
      prerequisites: { yellow: 2 },
      abbr: "IP",
      isFactionTech: true,
    },
    {
      nsidName: "krovoz-strike-teams",
      name: "Krovos Strike Teams",
      color: "yellow",
      prerequisites: { yellow: 2 },
      abbr: "KST",
      isFactionTech: true,
    },
    {
      nsidName: "local-contracts",
      name: "Local Contracts",
      color: "yellow",
      prerequisites: { yellow: 2 },
      abbr: "Local Con",
      isFactionTech: true,
    },
    {
      nsidName: "merged-replicators",
      name: "Merged Replicators",
      color: "yellow",
      prerequisites: { yellow: 2 },
      abbr: "Merged",
      isFactionTech: true,
    },
    {
      nsidName: "parallel-production",
      name: "Parallel Production",
      color: "yellow",
      prerequisites: { yellow: 1 },
      abbr: "Parallel",
      isFactionTech: true,
    },
    {
      nsidName: "recursive-worm",
      name: "Recursive Worm",
      color: "yellow",
      prerequisites: { yellow: 1 },
      abbr: "Worm",
      isFactionTech: true,
    },
    {
      nsidName: "sanctification-field",
      name: "sanctification Field",
      color: "yellow",
      prerequisites: { yellow: 3 },
      abbr: "Sanc Field",
      isFactionTech: true,
    },
    {
      nsidName: "seeker-drones",
      name: "Seeker Drones",
      color: "yellow",
      prerequisites: { yellow: 2 },
      abbr: "Seeker",
      isFactionTech: true,
    },
    {
      nsidName: "sentient-datapool",
      name: "Sentient Datapool",
      color: "yellow",
      prerequisites: { yellow: 2 },
      abbr: "Datapool",
      isFactionTech: true,
    },
    {
      nsidName: "vector-programs",
      name: "Vector Programs",
      color: "yellow",
      prerequisites: { yellow: 1 },
      abbr: "Vector",
      isFactionTech: true,
    },
    {
      nsidName: "voidwake-missiles",
      name: "Voidwake Missiles",
      color: "yellow",
      prerequisites: { yellow: 1 },
      abbr: "Void Missiles",
      isFactionTech: true,
    },
  ],
};